name: Vane-Angular-Mongo-Todo
framework: vane

handlers:
# Backend services using the shorthand syntax
- url: /todos 
  handler: GET:todo.dart:Todo.getAll 

- url: /todos 
  handler: POST:todo.dart:Todo.add

- url: /todos 
  handler: PUT:todo.dart:Todo.update

- url: /todos 
  handler: DELETE:todo.dart:Todo.delete 

# Equivalent alternatives to the above config  
#- url: /todos 
#  method: GET 
#  script: todo.dart
#  handler: Todo.getAll 
# 
#- url: /todos 
#  method: POST 
#  script: todo.dart
#  handler: Todo.add 
#   
#- url: /todos 
#  method: PUT 
#  script: todo.dart
#  handler: Todo.update 
#   
#- url: /todos 
#  method: DELETE 
#  script: todo.dart
#  handler: Todo.delete 
  
# Static content served by Nginx 
- url: /
  match: postregex
  static_dir: web

  